# Build stage
FROM node:20-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN mkdir -p /models
RUN npm run build

# Runtime stage
FROM node:20-slim
RUN npm install -g serve
WORKDIR /app
COPY --from=builder /app/dist /app
RUN chmod -R a+rX /app
EXPOSE 80
CMD ["serve", "-s", "/app", "-l", "80"]
