# Build stage
FROM node:20-slim AS builder
WORKDIR /app
ARG VITE_SRV_URL=http://localhost:8000
ARG VITE_TRAIN_MODE=false
ENV VITE_SRV_URL=${VITE_SRV_URL}
ENV VITE_TRAIN_MODE=${VITE_TRAIN_MODE}
COPY src/app/package*.json ./
RUN npm install
COPY src/app/ .
RUN mkdir -p /models
RUN npm run build

# Runtime stage
FROM node:20-slim
RUN npm install -g serve
WORKDIR /app
COPY --from=builder /app/dist /app
RUN chmod -R a+rX /app
EXPOSE 80
CMD ["serve", "-s", "/app", "-l", "80"]
