# Build stage
FROM node:20-slim AS builder
WORKDIR /app
COPY src/app/package*.json ./
RUN npm install
COPY src/app/ .
RUN rm -f public/models
# Note: we don't copy models here because they are streamed at runtime
RUN npm run build

# Runtime stage
FROM node:20-slim
RUN npm install -g serve
WORKDIR /app
COPY --from=builder /app/dist /app
COPY src/app/entrypoint.sh /entrypoint.sh
ENV APP_ROOT=/app
RUN chmod -R a+rX /app \
    && chmod +x /entrypoint.sh

EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
